[project]
name = "f4rys"
version = "0.1.0"
description = "Personal repo"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mnists>=0.4.1",
    "numpy>=2.3.1",
    "pillow>=11.2.1",
    "requests>=2.32.4",
]
